apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: remote
  labels:
    trainer.kubeflow.org/framework: remote
spec:
  mlPolicy:
    numNodes: 1
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  restartPolicy: Never
                  containers:
                    - name: node
                      image: remote-trainer:latest
                      imagePullPolicy: Never
                      command: []
                      envFrom:
                        - secretRef:
                            name: aws-secret
                        - secretRef:
                            name: firecrest-secret